services:
  - type: web
    name: shiksha-chatbot
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot_api:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
      - key: OPENROUTER_MODEL
        value: openai/gpt-4o-mini
